#!/bin/bash

git stash -q --keep-index

echo "Running Kitsu_AAC git pre-commit hook"

./gradlew ktlintFormat
./gradlew ktlint

RESULT=$?

git stash pop -q

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0